package com.onelpro.librelog.config;

import lombok.Data;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Version information provider.
 * Reads version and git commit information from application properties.
 */
@Data
@Component
public class VersionInfo {

    private final String version;
    private final String gitCommit;
    private final String gitCommitShort;

    public VersionInfo(@Value("${app.version:0.0.1-SNAPSHOT}") String version) {
        this.version = version;
        
        // Try to read git.properties if available (generated by git-commit-id-plugin)
        Properties gitProps = loadGitProperties();
        this.gitCommit = gitProps.getProperty("git.commit.id.full", "unknown");
        this.gitCommitShort = gitProps.getProperty("git.commit.id.abbrev", "unknown");
    }

    private Properties loadGitProperties() {
        Properties props = new Properties();
        try (InputStream is = getClass().getClassLoader().getResourceAsStream("git.properties")) {
            if (is != null) {
                props.load(is);
            } else {
                // Try to get from environment or system properties as fallback
                String commit = System.getenv("GIT_COMMIT");
                if (commit != null && !commit.isEmpty()) {
                    props.setProperty("git.commit.id.full", commit);
                    props.setProperty("git.commit.id.abbrev", commit.length() > 7 ? commit.substring(0, 7) : commit);
                }
            }
        } catch (IOException e) {
            // git.properties not available, try environment variables
            String commit = System.getenv("GIT_COMMIT");
            if (commit != null && !commit.isEmpty()) {
                props.setProperty("git.commit.id.full", commit);
                props.setProperty("git.commit.id.abbrev", commit.length() > 7 ? commit.substring(0, 7) : commit);
            }
        }
        return props;
    }

    public String getVersionDisplay() {
        return String.format("%s (%s)", version, gitCommitShort);
    }
}

