

name: GayPHX Music Submission & ISRC Manager
description: >
  Web application for artists to submit tracks to GayPHX, request ISRC assignment,
  and for admins to manage approvals, ISRC generation, and radio-ready catalog.

goals:
  - Empower LGBTQ+ artists to register and track their music.
  - Provide GayPHX with tools to manage submissions, assign ISRCs, and export data.
  - Integrate with GayPHX Radio (AzuraCast/LibreTime) for approved songs.

tech_stack:
  frontend: Next.js (React, TypeScript)
  backend: FastAPI (Python)
  database: PostgreSQL
  storage: S3-compatible bucket (MinIO)
  auth: Clerk or Auth.js (email magic link)
  deploy: Docker Compose
  integrations:
    - AzuraCast API
    - Email (SendGrid or SES)

environment_variables:
  - ISRC_COUNTRY
  - ISRC_REGISTRANT
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - DATABASE_URL
  - EMAIL_SMTP_URL
  - GAYPHX_API_KEY

notes: |
  This project powers music.gayphx.com — a community-focused platform where queer
  artists can upload songs, request ISRC codes, and track approvals. Admins can
  review, approve, assign ISRCs, and export metadata for integration with
  GayPHX Community Radio automation. All submissions are managed securely with
  artist dashboards, email notifications, and full audit logging.